### ISSUE TITLE
Mutation operations should be excluded

### ISSUE THREAD

**Issue by croutonn** [croutonn/graphql-codegen-plugin-typescript-swr#1]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Mutation operations should be excluded because they are not required by the SWR specification.

**Comment by aecorredor** [comment]
@croutonn I'm curious if you think this still applies today given `swr` now has https://swr.vercel.app/docs/mutation#useswrmutation.
