### ISSUE TITLE
Compilation error with swr 0.5.0

### ISSUE THREAD

**Issue by adarnon** [croutonn/graphql-codegen-plugin-typescript-swr#116]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Upgrading `swr` to `0.5.0` causes a TypeScript error in the files generated by `graphql-codegen-plugin-typescript-swr`. `ConfigInterface` and `keyInterface` have also been marked deprecated.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by eitoball** [comment]
Could you try to update swr to 1.0.x? If you still get error, please create new issue. Thank you.
