### ISSUE TITLE
Is anyone still maintaining this repository?

### ISSUE THREAD

**Issue by adarnon** [croutonn/graphql-codegen-plugin-typescript-swr#159]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

SWR v1 has just been released with breaking changes. Is anyone still maintaining this repo to fix the behavior?

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by eitoball** [comment]
We will release 0.7.0 with version 1.0.x of SWR.
