### ISSUE TITLE
Dependent fetching

### ISSUE THREAD

**Issue by baboons** [croutonn/graphql-codegen-plugin-typescript-swr#52]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**

Is it possible to use dependent fetching? If the support is there, could you give an example on how to use it? I've tried different way but haven't been able to make it work.

- **Other information**

```
function MyProjects() {
  const { data: user } = useSWR('/api/user')
  const { data: projects } = useSWR(() => '/api/projects?uid=' + user.id)
  // When passing a function, SWR will use the return
  // value as `key`. If the function throws or returns
  // falsy, SWR will know that some dependencies are not
  // ready. In this case `user.id` throws when `user`
  // isn't loaded.

  if (!projects) return 'loading...'
  return 'You have ' + projects.length + ' projects'
}
```

**Comment by croutonn** [comment]
Unless the `autogenSWRKey` option is enabled,  
the plug-in generates code that passes the raw `key` and `options` to the `useSWR()` and returns the raw result,  
so it should support Conditional Fetching in the specification.

If you have the `GetUser` and `GetProjects` query, the code looks like this:

```js
function MyProjects () {
  const { data: user } = sdk.useGetUser('/api/user')
  const { data: projects } = sdk.useGetProjects(() => '/api/projects?uid=' + user.id)
  if (!projects) return 'loading...'
  return 'You have ' + projects.length + ' projects'
}
```

If you can't use it, there is a high possibility of a bug, so I would appreciate it if you could respond!

**Comment by vitorcamachoo** [comment]
Hii, with `autogenSWRKey` enabled, how I achieve pendent requests ?
