### ISSUE TITLE
0.6.1 useInfiniteQuery signatures not correct

### ISSUE THREAD

**Issue by csprance** [croutonn/graphql-codegen-plugin-typescript-swr#89]
- **I'm submitting a ...**
  [ * ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Seems like in 0.61 the useInfiniteQuery signature has changed and no longer works. Rolling back to 0.5.1 causes the signature to accept the correct results again.

- **Other information**
 On 0.5.1:
![image](https://user-images.githubusercontent.com/7902617/106395877-a0fab900-63d2-11eb-987e-f019c0debecf.png)
On 0.6.1
![image](https://user-images.githubusercontent.com/7902617/106395893-ba036a00-63d2-11eb-84f9-c169926148f5.png)

**Comment by csprance** [comment]
Maybe it is correct I'm just using it wrong in the latest version and the docs haven't been updated. 
What am I missing?

**Comment by eitoball** [comment]
Did you solve this problem? As long as I looked at 0.6.1 screenshot, it says that `getKey` instead of `id` in the first argument of `useBlogIndexPageInfinite`.  Please try to use 0.7.1. If you get same error, please create new issue. Thank you.
